# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: yuikns/yarn:10

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - pwd
          - cd docs
          - pwd
          - yarn install
          - yarn build
          - ls -al .vuepress/dist/
  branches:
    fall2018:
      - step:
          script:
            - pwd
            - node -v
            - yarn -v
            - uname -a
            - cat /etc/debian_version
            - ls -al ~/.ssh
            - cd docs
            - pwd
            - yarn install
            - yarn build
            - ls -al .vuepress/dist
            - apt-get update && apt-get --yes install rsync
            - rsync -avzh --delete .vuepress/dist/ $CI_USER@sunlab.org:$SITE_BASE/teaching/cse6250/fall2018/
