# Site
title: Bigdata Bootcamp
header-img: image/background.jpg
description: Gatech CSE big data bootcamp

url: "http://www.sunlab.org"
baseurl: "/bigdata"
permalink: pretty

# Social network
twitter_username: SBootstrap 
github_username: cmanul
facebook_username: suhang
email: su_hang@live.com

# Markdown
markdown: redcarpet
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

redcarpet:
  extensions: [disable_indented_code_blocks, lax_spacing, with_toc_data, prettify, footnotes]

exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]

# page default
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
      author: "Sun Lab"